services:
     tenlomanchatbot:
       build: .
       expose:
         - "8080"
     nginx:
       image: nginx:latest
       ports:
         - "80:80"
       volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf
       depends_on:
         - tenlomanchatbot