name: Deploy to GCP Compute Engine

on:
  push:
    branches:
      - GCP

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set envvar
        env:
          VM_USER: ubuntu
          VM_IP:   35.240.138.116
        run: |
          echo "VM_USER=$VM_USER" >> $GITHUB_ENV
          echo "VM_IP=$VM_IP"     >> $GITHUB_ENV

      - name: Set up SSH
        run: |
          mkdir -p                               ~/.ssh
          echo "${{ secrets.VM_SSH_KEY_STR }}" > ~/.ssh/vm_ssh_key
          chmod 600                              ~/.ssh/vm_ssh_key
          ssh-keyscan -H "$VM_IP"             >> ~/.ssh/known_hosts

      - name: Deploy to VM
        env:
          PROJECT_DIR: ~/test2
          REPO_URL:    https://github.com/${{ github.repository }}.git
        run: |
          echo "VM_USER=$VM_USER" 
          echo "VM_IP=$VM_IP"
          echo "ssh -o StrictHostKeyChecking=no -i ~/.ssh/vm_ssh_key $VM_USER@$VM_IP  "
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/vm_ssh_key $VM_USER@$VM_IP << EOT
            set -eou pipefail
            
            # Clone or update repository
            if [ ! -d "$PROJECT_DIR" ]; then
              echo "Cloning repository..."
              git clone $REPO_URL -b GCP "$PROJECT_DIR"
            else
              echo "Updating repository..."
              cd "$PROJECT_DIR"
              git fetch origin
              git reset --hard origin/GCP
            fi
            
            cd "$PROJECT_DIR" || { echo "Failed to change directory to $PROJECT_DIR"; exit 1; }
            
            # Deploy application
            if [ -f "composeup.sh" ]; then
              echo "Running custom deployment script..."
              bash composeup.sh
            else
              echo "Running standard Docker Compose deployment..."
              docker-compose down || true
              docker-compose up --build -d
            fi
            
            # Show recent logs
            echo "Recent application logs:"
            docker-compose logs --tail=10
          EOT
