name: Deploy to GCP Compute Engine

on:
  push:
    branches:
      - GCP

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set envvar
        env:
          VM_USER: ${{ secrets.VM_USER }}
          VM_IP:   ${{ secrets.VM_IP }}
        run: |
          echo "VM_USER=$VM_USER" >> $GITHUB_ENV
          echo "VM_IP=$VM_IP"     >> $GITHUB_ENV

      - name: Set up SSH
        run: |
          mkdir -p                               ~/.ssh
          echo "${{ secrets.GCP_DEPLOY_KEY }}" > ~/.ssh/gcp_deploy_key
          chmod 600                              ~/.ssh/gcp_deploy_key
          ssh-keyscan -H "$VM_IP"             >> ~/.ssh/known_hosts

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/gcp_deploy_key "$VM_USER@$VM_IP" << 'EOT'
            set -e
            if [ ! -d "/home/$VM_USER/test2" ]; then
              git clone https://github.com/${{ github.repository }}.git -b GCP /home/$VM_USER/test2
            else
              cd /home/$VM_USER/test2
              git pull origin GCP
            fi
            cd /home/$VM_USER/test2 || { echo "Failed to change directory"; exit 1; }
            if [ -f "composeup.sh" ]; then
              bash composeup.sh
            else
              docker-compose down
              docker-compose up --build -d
            fi
            docker-compose logs --tail=10
          EOT
