name: Deploy to GCP Compute Engine

     on:
       push:
         branches:
           - master

     jobs:
       deploy:
         runs-on: ubuntu-latest
         steps:
           - name: Checkout code
             uses: actions/checkout@v4

           - name: Set up SSH
             env:
               SSH_PRIVATE_KEY: ${{ secrets.GCP_DEPLOY_KEY }}
             run: |
               mkdir -p ~/.ssh
               echo "$SSH_PRIVATE_KEY" > ~/.ssh/gcp_deploy_key
               chmod 600 ~/.ssh/gcp_deploy_key
               eval "$(ssh-agent -s)"
               ssh-add ~/.ssh/gcp_deploy_key

           - name: Deploy to VM
             env:
               VM_IP: ${{ secrets.VM_IP }}
               VM_USER: ${{ secrets.VM_USER }}
             run: |
               ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP << 'EOF'
               cd /home/$VM_USER/test2 || { echo "Directory not found, cloning..."; git clone https://github.com/LaloS1357/test2.git -b master /home/$VM_USER/test2; }
               cd /home/$VM_USER/test2
               git pull origin master
               bash composeup.sh
               EOF